# Generated by Django 4.2.1 on 2024-02-25 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_alter_resume_about_alter_skill_skill_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='specialization',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='type_of_employment',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='work_experience',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.DeleteModel(
            name='Specialization',
        ),
        migrations.DeleteModel(
            name='TypeOfEmployment',
        ),
        migrations.DeleteModel(
            name='WorkExperience',
        ),
    ]
