# Generated by Django 4.2.1 on 2024-02-25 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0001_initial'),
        ('work_experience', '0001_initial'),
        ('type_of_employment', '0001_initial'),
        ('specialization', '0001_initial'),
        ('resume', '0003_remove_resume_skill_remove_resume_specialization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='skill',
            field=models.ManyToManyField(to='skill.skill'),
        ),
        migrations.AddField(
            model_name='resume',
            name='specialization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='specialization.specialization'),
        ),
        migrations.AddField(
            model_name='resume',
            name='type_of_employment',
            field=models.ManyToManyField(to='type_of_employment.typeofemployment'),
        ),
        migrations.AddField(
            model_name='resume',
            name='work_experience',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='work_experience.workexperience'),
        ),
    ]
