# Generated by Django 4.2.1 on 2024-02-25 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work_experience', '0001_initial'),
        ('specialization', '0001_initial'),
        ('resume', '0004_resume_skill_resume_specialization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='specialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specialization.specialization'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='work_experience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work_experience.workexperience'),
        ),
    ]
