# Generated by Django 4.2.1 on 2024-02-05 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
