# Generated by Django 4.2.1 on 2024-02-27 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('type_of_employment', '0001_initial'),
        ('company', '0002_company_is_delete'),
        ('skill', '0001_initial'),
        ('specialization', '0001_initial'),
        ('resume', '0005_alter_resume_specialization_and_more'),
        ('work_experience', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('body', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('is_close', models.BooleanField(default=False)),
                ('is_delete', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('resumes', models.ManyToManyField(to='resume.resume')),
                ('rqd_skill', models.ManyToManyField(to='skill.skill')),
                ('rqd_specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specialization.specialization')),
                ('rqd_type_of_employment', models.ManyToManyField(to='type_of_employment.typeofemployment')),
                ('rqd_work_experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work_experience.workexperience')),
            ],
        ),
    ]
