# Generated by Django 4.2.1 on 2023-09-17 12:41

from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projects_total', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserAvatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_avatar_url', models.FileField(upload_to=user.models.user_avatar_url)),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='date_joinded',
            new_name='date_joined',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='reset_passwor_uuid_hash',
            new_name='reset_password_uuid_hash',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='knowledge_of_programming_language',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='work_experience',
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='projects_compleat',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='KnowledgeOfProgrammingLanguage',
        ),
        migrations.DeleteModel(
            name='WorkExperience',
        ),
        migrations.AddField(
            model_name='profile',
            name='employer_profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.employerprofile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_avatar',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.useravatar'),
        ),
    ]
