# Generated by Django 4.2.1 on 2023-09-19 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_employerprofile_useravatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_employee',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_employer',
            field=models.BooleanField(),
        ),
    ]
