# Generated by Django 4.2.1 on 2023-10-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_is_employee_alter_user_is_employer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='two_factor_auth_hash',
        ),
        migrations.AddField(
            model_name='user',
            name='otp_base32',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
