# Generated by Django 4.2.1 on 2023-10-21 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_useravatar_for_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useravatar',
            name='for_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.profile'),
        ),
    ]
