# Generated by Django 4.2.1 on 2023-12-13 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_useravatar_for_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='reset_password_uuid_hash',
        ),
    ]
