# Generated by Django 4.2.1 on 2024-01-07 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_employeespecialization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeespecialization',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
