# Generated by Django 4.2.1 on 2024-01-11 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_employeespecialization_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='employee_profile',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='employer_profile',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
        migrations.DeleteModel(
            name='EmployeeProfile',
        ),
        migrations.DeleteModel(
            name='EmployeeSpecialization',
        ),
        migrations.DeleteModel(
            name='EmployerProfile',
        ),
    ]
