# Generated by Django 4.2.1 on 2024-01-12 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_remove_profile_employee_profile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='second_name',
            new_name='last_name',
        ),
    ]
